ersion: '3.6'

services:
  db:
    image: percona/percona-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SiPuNi
    volumes:
      - ./percona_data:/var/lib/mysql

    ports:
      - "13306:3306"